import Galery from "@/app/components/galery";
import Nav from "@/app/components/layout/navigation/Nav";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
