import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./styles/variables.css";

import "./styles/global.css";
import Nav from "./components/layout/navigation/Nav";

const inter = Inter({ subsets: ["latin"] });
// const roboto = Roboto({ weight: ["500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={`${inter.className} ${roboto.className}`}>
       */}
      {/* <Nav /> */}
      <body className={`${inter.className} `}>{children}</body>
    </html>
  );
}
